// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrA1k0yTJLR3vRlY_GBxrQubQIeD2unGc',
    appId: '1:988407159344:web:c54b41c27c46598afa2bf5',
    messagingSenderId: '988407159344',
    projectId: 'fmss-e6463',
    authDomain: 'fmss-e6463.firebaseapp.com',
    storageBucket: 'fmss-e6463.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcgITqLLfQ8oELZWhJlHNaYaA2SKoG39Y',
    appId: '1:988407159344:android:81ae243e9a991392fa2bf5',
    messagingSenderId: '988407159344',
    projectId: 'fmss-e6463',
    storageBucket: 'fmss-e6463.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm4WoVXK-30c5Sw93IUNC-OIuEIgcmMN8',
    appId: '1:988407159344:ios:d4384ff2c118b115fa2bf5',
    messagingSenderId: '988407159344',
    projectId: 'fmss-e6463',
    storageBucket: 'fmss-e6463.appspot.com',
    iosClientId: '988407159344-jdteanlcosdv5b6o5u8cahag5ghsqbiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fundamentalscience',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm4WoVXK-30c5Sw93IUNC-OIuEIgcmMN8',
    appId: '1:988407159344:ios:d4384ff2c118b115fa2bf5',
    messagingSenderId: '988407159344',
    projectId: 'fmss-e6463',
    storageBucket: 'fmss-e6463.appspot.com',
    iosClientId: '988407159344-jdteanlcosdv5b6o5u8cahag5ghsqbiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fundamentalscience',
  );
}
